---
- name: Download nginx prometheus exporter
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.3.0/nginx-prometheus-exporter_1.3.0_linux_amd64.tar.gz
    dest: /tmp/nginx_exporter.tar.gz

- name: Extract nginx exporter
  unarchive:
    src: /tmp/nginx_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=0]

- name: Create nginx exporter systemd service
  copy:
    dest: /etc/systemd/system/nginx_exporter.service
    content: |
      [Unit]
      Description=NGINX Prometheus Exporter
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri http://127.0.0.1/stub_status
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Deploy Nginx default config with stub_status
  ansible.builtin.template:
    src: nginx-default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx


- name: Enable and start nginx exporter
  systemd:
    name: nginx_exporter
    enabled: yes
    state: started

